client_id = "2e83299418781073617c27b7ead34b48"
name = "YMMT Page Builder"
application_url = "https://ymmt-page-builder-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "write_products,read_products,read_content,write_content,write_metaobjects,read_metaobjects,write_metaobject_definitions"

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = [ "app/uninstalled" ]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://ymmt-page-builder-production.up.railway.app/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false
